apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-consul
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-consul
    spec:
      containers:
      - image: consul:1.3.1
        name: edgex-core-consul
        ports:
        - containerPort: 8400
        - containerPort: 8500
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-data
        - mountPath: /edgex/logs
          name: log-data
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      - name: log-data
        persistentVolumeClaim:
          claimName: log-data
      - name: consul-config
        persistentVolumeClaim:
          claimName: consul-config
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data
status: {}
