apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-app-service-configurable-rules
  name: edgex-app-service-configurable-rules
spec:
  ports:
  - name: "48100"
    port: 48100
    targetPort: 48100
  selector:
    io.kompose.service: edgex-app-service-configurable-rules
status:
  loadBalancer: {}
